#!/bin/bash
set -e

ENV=$1
MODEL_PATH=$2
BUCKET="wolever-jg-models"

if [ -z "$ENV" ] || [ -z "$MODEL_PATH" ]; then
    echo "Usage: ./publish-model [env] [path/to/model]"
    echo "Example: ./publish-model prod ./checkpoints-JGGame-v1/best.pth.tar"
    exit 1
fi

DEST="gs://$BUCKET/$ENV/best.pth.tar"

echo "Publishing model to $DEST..."
gsutil cp "$MODEL_PATH" "$DEST"
echo "Done."
